config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :activities
  resources :users
  
  get '/home' => 'pages#home'
  root to: 'activities#index'
  get '/beers' => 'beers#index'
  post '/beers' => 'beers#create'
  get '/beers/search' => 'beers#search'
  post '/beers/search' => 'beers#search'
  get '/beers/:id' => 'beers#show'
  get '/beers/:id/edit' => 'beers#edit'
  patch '/beers/:id' => 'beers#update'
  delete '/beers/:id' => 'beers#destroy'
  

  patch '/custom_beers/:id' => 'custom_beers#update'
  get '/custom_beers/new' => 'custom_beers#new'
  get '/custom_beers/:id' => 'custom_beers#show'
  post '/custom_beers' => 'custom_beers#create'
  get '/custom_beers/:id/edit' => 'custom_beers#edit'
  delete '/custom_beers/:id' => 'custom_beers#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninety9beers</title>
  <%= stylesheet_link_tag    'application', media: 'all'  %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lato:400,700', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>
</head>
<body>
  <div class="topbar animated fadeInLeftBig"></div>

    <!-- Header Starts -->
    <div class="navbar-wrapper">
      <div class="container">

        <div class="navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <!-- Logo Starts -->
              <div class="navbar-brand">
                <%= link_to image_tag("logo.png"), activities_path %>
              </div>
              <!-- #Logo Ends -->


              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

            </div>


            <!-- Nav Starts -->
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right scroll">
                  <% if user_signed_in? %>
                  <li><%= link_to 'Home', '/home' %></li>
                  <li><%= link_to "News Feed", activities_path %></li>
                   <li><%= link_to "Trophy Wall", "/users/#{current_user.id}" %></li>
                  <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">You<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                    </ul>
                  </li>
                   <li>
                    <div class="profile-image">
                      <% if current_user.image_url %>
                        <%= image_tag current_user.image_url(:preview) %>
                      <% else %>
                        <%= image_tag "/assets/genuser.png" %>
                      <% end %>
                    </div>
                    </li>
                  <% else %>
                    <li><%= link_to "Sign up", new_user_registration_path %></li>
                    <li><%= link_to "Login", new_user_session_path %></li>
                  <% end %>
              </ul>
            </div> 


          </div>
        </div>

      </div>
    </div>

    <!-- #Header Starts -->
    <% flash.each do |key, value| %>
      <div class="alert devise-alert beer-alert alert-<%= key %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <ul>
          <li>
            <%= value %>
          </li>
        </ul>
      </div>
    <% end %>
    <%= yield %>


  <!-- Footer Starts -->
  <div class="footer text-center">
    <i class="fa fa-copyright" aria-hidden="true"></i> 2016 99Beers
    <h5>Powered by <%= link_to "Untappd", "https://untappd.com/" %></h5>
    <h5>99 Beers, a final project app created by <%= link_to "Kylie Tram Le", "https://www.linkedin.com/in/kylietramle" %></h5>
     <h5>Read about my learning progress here on my <%= link_to "Coding Blog", "https://kylietramle.wordpress.com/" %></h5>
  </div>
  <!-- # Footer Ends -->

  <script type="text/javascript">
   $(function() {
      $('#stars_dropdown').barrating({
        theme: 'fontawesome-stars'
      });
   });
</script>
  

</body>
</html>